// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkqTxGd5fspi_clJHK4IuamryCiF7d774',
    appId: '1:72255004993:web:83ef26db685fc82a4181c0',
    messagingSenderId: '72255004993',
    projectId: 'fruitshub-47b51',
    authDomain: 'fruitshub-47b51.firebaseapp.com',
    storageBucket: 'fruitshub-47b51.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0zs0_xIPCWfjCdTOYbYUOBp9g7Wb0W_s',
    appId: '1:72255004993:android:c96ec59ddd5bd9314181c0',
    messagingSenderId: '72255004993',
    projectId: 'fruitshub-47b51',
    storageBucket: 'fruitshub-47b51.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAjpYz1x2AljnhpDQuwDs0h88kXQg0tY4',
    appId: '1:72255004993:ios:9228f8fad97560f84181c0',
    messagingSenderId: '72255004993',
    projectId: 'fruitshub-47b51',
    storageBucket: 'fruitshub-47b51.appspot.com',
    iosBundleId: 'com.example.fruits',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAjpYz1x2AljnhpDQuwDs0h88kXQg0tY4',
    appId: '1:72255004993:ios:9228f8fad97560f84181c0',
    messagingSenderId: '72255004993',
    projectId: 'fruitshub-47b51',
    storageBucket: 'fruitshub-47b51.appspot.com',
    iosBundleId: 'com.example.fruits',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkqTxGd5fspi_clJHK4IuamryCiF7d774',
    appId: '1:72255004993:web:5abe1ae012f677bc4181c0',
    messagingSenderId: '72255004993',
    projectId: 'fruitshub-47b51',
    authDomain: 'fruitshub-47b51.firebaseapp.com',
    storageBucket: 'fruitshub-47b51.appspot.com',
  );
}
